name: &name Meredith Lane
author: *name
title: software && sounds 
email: meredith@softwaresounds.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal site for Meredith Lane, a software and sound engineer living in
  Sydney, Australia. Accessibility, Web Design, Sound Design.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://softwaresounds.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mrrdth

date_format: "%B %-d, %Y"
timezone: Australia/Sydney

# Build settings
plugins:
  - jekyll-feed

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
