name: &name Meredith Lane

title: *name
author: *name

description: "The site of Meredith Lane, a software engineer and musician living in Sydney."
baseurl: ""
paginate: 10

url: "https://softwaresounds.com"

date_format: "%B %-d, %Y"
timezone: Australia/Sydney


markdown: kramdown
permalink: pretty
highlighter: rouge
